### ISSUE TITLE
Implement endpoint for management of referrals

### ISSUE THREAD

**Issue by JAjorgbor** [haqqman/hostelcloud-api#354]
Implement CRUD endpoints for managing existing referrals in the Hostel Guru Console

**Comment by suleinsights** [comment]
> saved refferals in the Hostelguru console

@JAjorgbor pay attention to your typography always. `existing referrals in the Hostel Guru Console`

**Comment by namikaze-dev** [comment]
@JAjorgbor Can I see the ui?

**Comment by anaotaye** [comment]
@namikaze-dev 
![Referrals-—-Hostel-Guru-Console](https://github.com/haqqman/hostelcloud-api/assets/99747423/d6d5f632-9c6c-4448-807d-b8940f83d6b2)
