### ISSUE TITLE
Implement select field for bank name in hostelguru portal

### ISSUE THREAD

**Issue by JAjorgbor** [haqqman/hostelcloud-api#355]
Implement a select field for bank name in the portal referral page. Take note of the screenshot below
![image](https://github.com/haqqman/hostelcloud-api/assets/93437152/0793cd6f-1630-4e94-b7ef-c9a3804abb88)

**Comment by namikaze-dev** [comment]
@suleinsights Paystack provides a free api to get account name/details from provided account number and bank name.
