### ISSUE TITLE
Develop console referrals page

### ISSUE THREAD

**Issue by JAjorgbor** [haqqman/hostelcloud-api#356]
Develop page for managing referrals in the webconsole. This page would be responsible for carrying out CRUD operations on referrals made from the portal.

**Comment by JAjorgbor** [comment]
@suleinsights Please kindly recommnend a UI for the page  in question

**Comment by anaotaye** [comment]
@JAjorgbor You assigned this to me?

**Comment by suleinsights** [comment]
> You assigned this to me?

Yes @anaotaye, that's because you will be the one to work on the issue.

**Comment by suleinsights** [comment]
@JAjorgbor what do you think?

![2024-05-17_21-51-51](https://github.com/haqqman/hostelcloud-api/assets/14318956/ecd5ca90-66c7-4e91-bc61-1faa5d7022c6)
![2024-05-17_21-56-32](https://github.com/haqqman/hostelcloud-api/assets/14318956/357af496-5cbb-4711-b296-1c28f8ec8504)

**Comment by JAjorgbor** [comment]
> @JAjorgbor what do you think?
> 
> ![2024-05-17_21-51-51](https://private-user-images.githubusercontent.com/14318956/331730371-ecd5ca90-66c7-4e91-bc61-1faa5d7022c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjA1ODUsIm5iZiI6MTcxNjA2MDI4NSwicGF0aCI6Ii8xNDMxODk1Ni8zMzE3MzAzNzEtZWNkNWNhOTAtNjZjNy00ZTkxLWJjNjEtMWZhYTVkNzAyMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE5MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMmY3Nzk1NDkyNTdlYjIxOTEzNGE2NzJjYzMyMDNiMzllNzcyMjQ3N2ZkYTU3Yzc3NjI4NTM1OWY3ZWFiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvr14-FtH4vNG3aYzbaOojCQEYG399dY8gp7_dLpfWU) ![2024-05-17_21-56-32](https://private-user-images.githubusercontent.com/14318956/331730386-357af496-5cbb-4711-b296-1c28f8ec8504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjA1ODUsIm5iZiI6MTcxNjA2MDI4NSwicGF0aCI6Ii8xNDMxODk1Ni8zMzE3MzAzODYtMzU3YWY0OTYtNWNiYi00NzExLWIyOTYtMWMyOGY4ZWM4NTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE5MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYTZkMWZjZmVkYmY0ZjQyMDc4MWE2OTE0YzkwNDAwZWRmY2FlMmY2NzBhODBlYzA2N2Y0ZTJhOTcyOWFlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mPpCCxllJLb90-emzYP8Q9du9TbS5AKCMcZWnVK2YUY)

Looks fine @suleinsights
